# Generated by Django 3.1.6 on 2021-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210218_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
