# Generated by Django 3.1.6 on 2021-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
