# Generated by Django 3.1.6 on 2021-02-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210218_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='image_student.jpg', upload_to=''),
        ),
    ]
