# Generated by Django 3.1.6 on 2021-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210218_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='image_students.jpg', upload_to=''),
        ),
    ]
