# Generated by Django 3.1.6 on 2021-02-18 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20210218_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='teather',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 2, 18)),
        ),
        migrations.AddField(
            model_name='teather',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teather',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
