# Generated by Django 3.1.6 on 2021-02-19 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20210218_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 2, 19)),
        ),
        migrations.AlterField(
            model_name='teather',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 2, 19)),
        ),
    ]
