# Generated by Django 3.1.6 on 2021-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_auto_20210219_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
