# Generated by Django 3.1.6 on 2021-02-19 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_about_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('birthday', models.DateField(verbose_name=datetime.date(2021, 2, 19))),
                ('group', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('birthday', models.DateField(verbose_name=datetime.date(2021, 2, 19))),
                ('group', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('birthday', models.DateField(verbose_name=datetime.date(2021, 2, 19))),
                ('group', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='About_school',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teather',
        ),
    ]
