# Generated by Django 3.1.6 on 2021-02-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20210219_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_parent',
            name='email',
            field=models.EmailField(blank=True, default='не указан', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile_student',
            name='email',
            field=models.EmailField(blank=True, default='не указан', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='email',
            field=models.EmailField(blank=True, default='не указан', max_length=254, null=True),
        ),
    ]
