# Generated by Django 3.1.6 on 2021-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20210219_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_parent',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile_student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile_parent',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_parent',
            name='last',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_student',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_student',
            name='last',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='last',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
