# Generated by Django 3.1.6 on 2021-02-20 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_auto_20210219_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_parent',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 20)),
        ),
        migrations.AlterField(
            model_name='profile_student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 20)),
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 20)),
        ),
    ]
