# Generated by Django 3.1.6 on 2021-02-23 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20210223_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_teacher',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='lesson_school',
            name='points',
            field=models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='profile_parent',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 24)),
        ),
        migrations.AlterField(
            model_name='profile_student',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 24)),
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 24)),
        ),
    ]
