# Generated by Django 3.1.6 on 2021-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_auto_20210224_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_school',
            name='image_lesson',
            field=models.ImageField(default='lesson_image.png', upload_to=''),
        ),
    ]
