# Generated by Django 3.1.6 on 2021-02-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_auto_20210224_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_parent',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_student',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
