# Generated by Django 3.1.6 on 2021-02-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0024_auto_20210224_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_parent',
        ),
    ]
