# Generated by Django 3.1.6 on 2021-02-26 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0027_remove_lesson_school_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile_student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile_student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile_student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='phone',
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 2, 26)),
        ),
    ]
