# Generated by Django 3.1.6 on 2021-02-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0028_auto_20210226_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_school',
            name='image_lesson',
        ),
        migrations.CreateModel(
            name='Points_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.lesson_school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.profile_student')),
            ],
        ),
    ]
