# Generated by Django 3.1.6 on 2021-03-01 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0029_auto_20210226_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2021, 3, 1)),
        ),
    ]
