# Generated by Django 3.1.6 on 2021-03-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0032_lesson_school_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_teacher',
            name='lesson',
        ),
    ]
