# Generated by Django 3.1.6 on 2021-03-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0033_remove_profile_teacher_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_school',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diary.profile_student'),
            preserve_default=False,
        ),
    ]
