# Generated by Django 3.1.6 on 2021-03-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0034_lesson_school_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='last',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='last',
        ),
    ]
