# Generated by Django 3.1.6 on 2021-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0035_auto_20210303_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_school',
            name='student',
        ),
        migrations.AddField(
            model_name='lesson_school',
            name='student',
            field=models.ManyToManyField(to='diary.Profile_student'),
        ),
    ]
